-- 20240520000000_music_api_schema.sql

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create ENUMS
CREATE TYPE profile_role AS ENUM ('artist', 'listener', 'admin');

-- Create Tables
-- 1. Profiles (extending auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    role profile_role DEFAULT 'listener',
    website TEXT,
    bio TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- 2. Genres
CREATE TABLE IF NOT EXISTS public.genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Albums
CREATE TABLE IF NOT EXISTS public.albums (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    artist_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    genre_id BIGINT REFERENCES public.genres(id) ON DELETE SET NULL,
    cover_url TEXT,
    release_date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tracks
CREATE TABLE IF NOT EXISTS public.tracks (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    album_id UUID REFERENCES public.albums(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    duration INTEGER NOT NULL, -- in seconds
    track_number INTEGER,
    file_url TEXT NOT NULL,
    lyrics TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Playlists
CREATE TABLE IF NOT EXISTS public.playlists (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Playlist Tracks (Junction)
CREATE TABLE IF NOT EXISTS public.playlist_tracks (
    playlist_id UUID REFERENCES public.playlists(id) ON DELETE CASCADE NOT NULL,
    track_id UUID REFERENCES public.tracks(id) ON DELETE CASCADE NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (playlist_id, track_id)
);

-- 7. Likes / Favorites
CREATE TABLE IF NOT EXISTS public.track_likes (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    track_id UUID REFERENCES public.tracks(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user_id, track_id)
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlist_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.track_likes ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Profiles: Anyone can view, only owner can update
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Genres: Anyone can view, only admins can modify (admin check needs a role logic or service role)
CREATE POLICY "Genres are viewable by everyone" ON public.genres FOR SELECT USING (true);

-- Albums: Anyone can view, artists can manage their own
CREATE POLICY "Albums are viewable by everyone" ON public.albums FOR SELECT USING (true);
CREATE POLICY "Artists can insert their own albums" ON public.albums FOR INSERT WITH CHECK (
    auth.uid() = artist_id AND (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'artist'
);
CREATE POLICY "Artists can update their own albums" ON public.albums FOR UPDATE USING (
    auth.uid() = artist_id
);

-- Tracks: Anyone can view, artists can manage theirs
CREATE POLICY "Tracks are viewable by everyone" ON public.tracks FOR SELECT USING (true);
CREATE POLICY "Artists can insert tracks into their albums" ON public.tracks FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.albums WHERE id = album_id AND artist_id = auth.uid())
);

-- Playlists: Public ones viewable by everyone, private only by owner
CREATE POLICY "Public playlists are viewable by everyone" ON public.playlists FOR SELECT USING (is_public = true OR auth.uid() = owner_id);
CREATE POLICY "Users can manage their own playlists" ON public.playlists FOR ALL USING (auth.uid() = owner_id);

-- Playlist Tracks: Related to playlist ownership
CREATE POLICY "Users can manage tracks in their playlists" ON public.playlist_tracks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.playlists WHERE id = playlist_id AND owner_id = auth.uid())
);

-- Likes: Users manage their own likes
CREATE POLICY "Users can view track likes" ON public.track_likes FOR SELECT USING (true);
CREATE POLICY "Users can manage their own track likes" ON public.track_likes FOR ALL USING (auth.uid() = user_id);

-- Create some default genres
INSERT INTO public.genres (name, slug) VALUES 
('Afrobeats', 'afrobeats'),
('Amapiano', 'amapiano'),
('Hip Hop', 'hip-hop'),
('Reggae', 'reggae'),
('Jazz', 'jazz')
ON CONFLICT (slug) DO NOTHING;

-- Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_albums_artist_id ON public.albums(artist_id);
CREATE INDEX IF NOT EXISTS idx_tracks_album_id ON public.tracks(album_id);
CREATE INDEX IF NOT EXISTS idx_playlist_tracks_track_id ON public.playlist_tracks(track_id);
CREATE INDEX IF NOT EXISTS idx_playlists_owner_id ON public.playlists(owner_id);