-- 20240520000001_track_plays.sql

CREATE TABLE IF NOT EXISTS public.track_plays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    track_id UUID REFERENCES public.tracks(id) ON DELETE CASCADE NOT NULL,
    played_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS: Only admins/system or the user can view their plays
ALTER TABLE public.track_plays ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see their own track plays" ON public.track_plays FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Anyone can log a track play" ON public.track_plays FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.uid() IS NULL);

-- Index for analytics performance
CREATE INDEX IF NOT EXISTS idx_track_plays_track_id ON public.track_plays(track_id);
CREATE INDEX IF NOT EXISTS idx_track_plays_user_id ON public.track_plays(user_id);
CREATE INDEX IF NOT EXISTS idx_track_plays_played_at ON public.track_plays(played_at);